apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook-{{ $.Values.global.env }}
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: guestbook
    server: {{ $.Values.global.spec.destination.server }}
  source:
    path: guestbook
    repoURL: 'https://github.com/argoproj/argocd-example-apps.git'
    targetRevision: 53e28ff20cc530b9ada2173fbbd64d48338583ba
  sources: []
  project: {{ $.Values.global.spec.project }}
  syncPolicy:
    syncOptions:
    - CreateNamespace=true      