apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbit-consumer-{{ $.Values.global.env }}
  namespace: argocd
spec:
  project: {{ $.Values.global.spec.project }}
  sources:
  - repoURL: 'https://github.com/stfc/SCD-OpenStack-Utils.git'
    path: charts/rabbit-consumer
    targetRevision: b9cd82fcbb07d14bded62e0dbe3eb51bc7f15f4c
    helm:
      valueFiles:
      - $values/{{ $.Values.global.env }}-values/rabbit-consumer-values.yaml
  - repoURL: 'https://github.com/stfc/cloud-deployed-apps.git'
    targetRevision: {{ $.Values.global.spec.source.targetRevision }}
    ref: values
  destination:
    server: {{ $.Values.global.spec.destination.server }}
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true