consumer:
  logLevel: DEBUG
  image:
    repository: rabbit-consumer
    tag: local
    # This allows us to build the image locally and use it in the chart
    pullPolicy: Never

  aquilon:
    defaultPrefix: vm-openstack-Dev-

  rabbitmq:
    host: dev-openstack.stfc.ac.uk

  openstack:
    authUrl: https://dev-openstack.stfc.ac.uk:5000/v3
    computeUrl: https://dev-openstack.stfc.ac.uk:8774/v2.1
    projectId: c9aee696c4b54f12a645af2c951327dc

kerberosSidecar:
  principle: "HTTP/dev-service1.nubes.rl.ac.uk"
